site_name: BetePHP
theme_dir: cinder
pages:
- 'Home': 'index.md'
- 'Get started':
    - 'Install': 'intro/install.md'
    - 'Overview': 'intro/overview.md'
    - 'Hello World!': 'intro/hello-world.md'
    - 'Http': 'intro/http.md'
    - 'Console': 'intro/console.md'
- 'Components':
    - 'Validator': 'component/validation.md'
    - 'Log': 'component/log.md'
    - 'Session & Cookie': 'component/session-cookie.md'
    - 'Redis': 'component/redis.md'
    - 'How to write your own component': 'component/extension.md'
- 'Database':
    - 'Database get started': 'database/intro.md'
    - 'Query Builder': 'database/query-builder.md'
