site_name: BetePHP
theme_dir: cinder
pages:
- '首页': 'index.md'
- '入门':
    - '安装': 'intro/install.md'
    - '预览': 'intro/overview.md'
    - '开发第一个功能': 'intro/first-feature.md'
- '运行模式': 
    - '介绍': 'runtime/intro.md'
    - '路由': 'web/route.md'
    - '中间件': 'web/middleware.md'
    - '请求相应处理': 'web/request.md'
- 'Web': 
    - '介绍': 'web/intro.md'
    - '路由': 'web/route.md'
    - '中间件': 'web/middleware.md'
    - '请求相应处理': 'web/request.md'
- '命令行':
    - '介绍': 'console/intro.md'
    - '请求相应处理': 'console/request.md'
    - '代码生成器': 'console/make.md'
- '组件':
    - '验证': 'component/validation.md'
    - '日志': 'component/log.md'
    - 'Session & Cookie': 'component/session-cookie.md'
    - 'Redis': 'component/redis.md'
    - '视图': 'component/view.md'
    - '如何写一个组件': 'component/extension.md'
- '数据库':
    - '数据库入门': 'database/intro.md'
    - 'Query Builder': 'database/query-builder.md'
    - 'Model': 'database/model.md'
- '其他':
    - '错误处理': 'other/exception-handler.md'
