site_name: BetePHP
theme_dir: cinder
pages:
- '首页': 'index.md'
- '入门':
    - '安装': 'intro/install.md'
    - '框架预览': 'intro/overview.md'
    - 'Hello World!': 'intro/hello-world.md'
    - 'Http': 'intro/http.md'
    - 'Console': 'intro/console.md'
- '组件':
    - '验证': 'component/validation.md'
    - '日志': 'component/log.md'
    - 'Session & Cookie': 'component/session-cookie.md'
    - 'Redis': 'component/redis.md'
    - '如何编写自己的组件': 'component/extension.md'
- '数据库':
    - '数据库入门': 'database/intro.md'
    - 'Query Builder': 'database/query-builder.md'
